// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmIrISAKPX6TJN0xSJPDQVahcpd1fdSMQ',
    appId: '1:692025050232:web:c1ac3f58b6ca205f6cd98d',
    messagingSenderId: '692025050232',
    projectId: 'tescom-helpdesk',
    authDomain: 'tescom-helpdesk.firebaseapp.com',
    storageBucket: 'tescom-helpdesk.firebasestorage.app',
    measurementId: 'G-ZVTRWDFS1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3qijczolH1IUkaZvCRNeEcg3_JTt5TwQ',
    appId: '1:692025050232:android:f3c4a705886c90ec6cd98d',
    messagingSenderId: '692025050232',
    projectId: 'tescom-helpdesk',
    storageBucket: 'tescom-helpdesk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXcqYY0jKH4uqduLfHnlFu-HThP72e0T0',
    appId: '1:692025050232:ios:3568afcbf621a4ff6cd98d',
    messagingSenderId: '692025050232',
    projectId: 'tescom-helpdesk',
    storageBucket: 'tescom-helpdesk.firebasestorage.app',
    iosBundleId: 'com.example.tescomHelpdesk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXcqYY0jKH4uqduLfHnlFu-HThP72e0T0',
    appId: '1:692025050232:ios:3568afcbf621a4ff6cd98d',
    messagingSenderId: '692025050232',
    projectId: 'tescom-helpdesk',
    storageBucket: 'tescom-helpdesk.firebasestorage.app',
    iosBundleId: 'com.example.tescomHelpdesk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmIrISAKPX6TJN0xSJPDQVahcpd1fdSMQ',
    appId: '1:692025050232:web:ff828c463b5930026cd98d',
    messagingSenderId: '692025050232',
    projectId: 'tescom-helpdesk',
    authDomain: 'tescom-helpdesk.firebaseapp.com',
    storageBucket: 'tescom-helpdesk.firebasestorage.app',
    measurementId: 'G-KVXCFN3SMB',
  );
}
